version: '3.8'

services:

  app:
    image: ms-logistica:latest
    container_name: ms-logistica
    build:
      context: .
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'logistica'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'

volumes:
  logistica: